# SQL TUTORIAL

## What is SQL?

1. SQL stands for Structured Query Language
2. SQL lets you access and manipulate databases
3. SQL became a standard of the American National Standards Institute (ANSI) in 1986, and of the International Organization for Standardization (ISO) in 1987

## What Can SQL do?

* SQL can execute queries against a database
* SQL can retrieve data from a database
* SQL can insert records in a database
* SQL can update records in a database
* SQL can delete records from a database
* SQL can create new databases
* SQL can create new tables in a database
* SQL can create stored procedures in a database
* SQL can create views in a database
* SQL can set permissions on tables, procedures, and views

## Using SQL in Your Web Site

> To build a web site that shows data from a database, you will need:
>> An RDBMS database program (i.e. MS Access, SQL Server, MySQL)
>> To use a server-side scripting language, like PHP or ASP
>>> To use SQL to get the data you want
>>> To use HTML / CSS to style the page

# Link to SQL TUTORIAL

[W3SCHOLLS](https://www.w3schools.com/sql/default.asp)

# FUN TIME

![1](https://lol24.ee/public/pics/264043/264043909_0.gif)
![2](https://www.mapsnbags.com/wp-content/uploads/2018/11/funny-travel-meme-girl-running.jpg)


```
<!DOCTYPE html>
<html>
<body>

<h2>An Unordered HTML List</h2>

<ul>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ul>  

<h2>An Ordered HTML List</h2>

<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol> 

</body>
</html>
```


# TABLE

|CustomerID|CustomerName|ContactName|   Address  |  City  |PostalCode|Country|
|----------|------------|-----------|------------|--------|----------|-------|
|     1    |Alfred      |Maria      |Obere Str.57|Berlin  |12209	   |Germany|
|     2    |Anna        |Anna       |Lavada Str.6|México  |05021	   |Mexico |
|     3	   |Antonio     |Antonio    |Mataderos 12|México  |05023     |Mexico |